### ISSUE TITLE
Check compilation for docs.rs build

### ISSUE THREAD

**Issue by myOmikron** [443eb9/bevy_entitiles#10]
The documentation does not build on docs.rs, you can check the status of the build at https://docs.rs/crate/bevy_entitiles/0.3.0/builds

**Comment by 443eb9** [comment]
I've already known this issue but I have no idea why this would happen. It says the platform is not supported. I guess #8 may be related to this. The next version may be built successfully.

**Comment by 443eb9** [comment]
Fixed in 0.4.0
