### ISSUE TITLE
Other: Examples aren't really working "out of the box", maybe they could use more docs

### ISSUE THREAD

**Issue by RobertoMaurizzi** [443eb9/bevy_entitiles#13]
## Description
I tried cloning the repository then running some of the provided examples, however they either don't run, don't render anything or render things I'm not sure are right.

## Reproduction
Clone the repo in a new directory, then run:

## ldtk_wfc

run with `cargo run -r --example ldtk_wfc --features="algorithm ldtk physics"`

Compiles out of the box and doesn't show any warning on the console (except one for an AmbientLight that wasnt' registered in the type registry) but then the output is the following:

![image](https://github.com/443eb9/bevy_entitiles/assets/451686/4fdb06cd-41f2-4150-9bd2-c73f56af08ea)

## ldtk

This example isn't straightforward to run even after inspecting the code. 
run with: `cargo run -r --example ldtk --features="debug ldtk physics"`

When running it right after cloning, it panics because it searches for an `assets/ldtk/ignore grid_vania.ldtk`
If I rename the existing `assets/ldtk/grid_vania.ldtk` to `assets/ldtk/ignore grid_vania.ldtk`, the app runs but I get this:

![image](https://github.com/443eb9/bevy_entitiles/assets/451686/40a82338-4d82-40f0-b45e-7fab25c535db)

I also noticed that the example's code mention not having finalbossblues-icons_full_16.png available, but it's still there in the repo inside assets/ldtk

```
❯ git log assets/ldtk/finalbossblues-icons_full_16.png
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
commit 83c6144e79023e7dbb0e40d51ec3392e39e307fa ┃
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Author: 443eb9#C <443eb9@gmail.com>
Date:   Tue Dec 19 18:38:31 2023 +0800

    Uploaded ldtk asstes.
```

To make sure the problem wasn't the asset, I saved LDTk 1.5.3's Gridvania sample in the assets/ldtk directory as "ignore etc.", but if I run the example again, I get the same result as above.

### wfc

run with: `cargo run -r --example wfc --features="algorithm"`

Here the application;s output  might be correct, but it's not clear.

![image](https://github.com/443eb9/bevy_entitiles/assets/451686/5b7a4f3e-bc7c-40ac-9dd8-34b6e881cf98)

### wfc_pattern

run with: `cargo run -r --example wfc_pattern --features="algorithm"`

Here apparently nothing happens... but if you read the example's source there's a comment about removing some lines, running the example, then restoring them... and after I did that I actually got an output very much like the wfc example above (but with a smaller map, so they're probably both correct)

## Suggestion
Maybe we should have a README.md for the examples (or separate the examples in directories and have a README.md in each of them) where to list any requirement to run an example, the compilation command and the expected output, like I've seen done in other projects.

## Versions
 - OS: SystemInfo { os: "Windows 11 Pro", kernel: "22621", cpu: "Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz", core_count: "8", memory: "15.8 GiB" }
 - Graphics: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Laptop GPU", vendor: 4318, device: 9373, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "546.33", backend: Vulkan }
 - Entitiles version: git clone of latest master fea6608cd665e7d

**Comment by 443eb9** [comment]
Well, seems that all of these examples are working as expected. But your issue do remind me to write more documents about the examples.

## ldtk_wfc

You need to move the small cube around using the arrow keys, and once it enters another level/area, the result will appear. Or you can change the mode at line 118 to `SingleMap` then you will see an entire map which is the result of the algorithm.

## ldtk

The finalbossblues-icons_full_16.png is actually not available. The image in `assets/` is actually a blank white image. And what you need to modify is the file name at line 72. Change `ignore grid_vania.ldtk` -> `grid_vania.ldtk`.

## wfc

It works, the result is correct.

## wfc_pattern

It works. The result should be similar to `wfc`. If you read the code above the comments that tells you to save something, you will see some for loops which is converting the `test_wfc.png` into tilemap patterns. Once the algorithm is finished, these patterns will be filled into the right place on a tilemap. So the result will be generally a larger version of `wfc`.

**Comment by RobertoMaurizzi** [comment]
I did some tests: for ldtk_wfc i is mostly as you said, however:
1. the map squares are only to the right and top of the player's starting point
2. they don't appear until you exit the first square at the top or right
So it's very easy to simply go around (down or left, but even to the right or top for a bit) and think that nothing is happening 😅

For the ldtk example. I tried editing the file name to use your grid_vania.ldtk but I got the same result as before, empty screen with green/red lines for the rooms (I guess) and blue for the size of the viewport, but no tiles in sight, white or otherwise :-( 
I'm curious to see a screenshot of how it should look, if you can add one somewhere (even here)

**Comment by 443eb9** [comment]
> a screenshot of how it should look

The `LDtk` section in `Show Cases & Performance` in README.md shows these expected results. The left one is `ldtk.rs` and the gif on the right is `ldtk_wfc.rs`.

> but no tiles in sight, white or otherwise

The LDtk example needs to press some keys to let the level spawn. See the [`load`](https://github.com/443eb9/bevy_entitiles/blob/master/examples/ldtk.rs#L136) function for more information.

> they don't appear until you exit the first square at the top or right

Yes it's a bug.

> the map squares are only to the right and top of the player's starting point

The latest master branch had used `SingleMap` as default. Each pattern should be 16*16 so you can check if the mode is not the one you expected.

**Comment by RobertoMaurizzi** [comment]
I understand, the problem remains that if a user want to check how it works and compile an example to check if it does something useful to then eventually I start to study the code... they won't.
I started reading the code of ldtk.rs and tried to copy the asset file with the expected name, then to save a new gridvania level in its place from LDTk... and it still didn't work.

A user interested in using the crate won't understand if they did something wrong/there's a problem with their system, or the code is broken.

Still now I have no idea how to obtain the image and gif here https://github.com/443eb9/bevy_entitiles?tab=readme-ov-file#ldtk since they are completely different from what I got even after reading the code and copying files.

If I have time in the next week to try and understand how to set up something that can work out of the box I'll send you a PR with it, if you're interested.

**Comment by 443eb9** [comment]
The incomplete document and inappropriate examples are really confusing... Sorry for the inconvenience... If you would like to, you can ping me in the thread in discord tomorrow evening(UTC+8), and I will try to fix this issue. Communicating in github issues are really inefficient and wastes much time.

> A user interested in using the crate won't understand if they did something wrong/there's a problem with their system, or the code is broken.

Yeah, I think no one would read the code they don't interested about. So examples are used to help users to judge if this crate or some functionality is useful to them.

> If I have time in the next week to try and understand how to set up something that can work out of the box I'll send you a PR with it, if you're interested.

Thank you very much for being willing to send a PR to address these issues!

**Comment by Ladvien** [comment]
Just adding my two cents here--It may be helpful to keep this issue open until addressed.  

I really appreciate `bevy_entitiles `, as it has massive potential and 443eb9 seems to keep it up to date (which is amazing ❤️ ).  But that stated, I've lost a couple days to lack of documentation (#18).  Some of that's probably my inexperience, but making deficits visible until addressed would most likely increase adoption.

One other note, although Github issues are a bit difficult for effective communication, the added benefit is they provide guidance to anyone depending on the crate.  The conversation is a bit of organic documentation.  Again, just my two cents.

Thank you again 443eb9! 🤘
