### ISSUE TITLE
Error compiling for webassembly

### ISSUE THREAD

**Issue by martinlindhe** [443eb9/bevy_entitiles#17]
**Description**

Error compiling for webassembly

**Reproduction**

1. comment out trace_tracy dependency in Cargo.toml as ittracy-client-sys v0.22.2 wont compile for wasm

2. `cargo build --target wasm32-unknown-unknown --example pathfinding --features algorithm`

**Versions**
 - OS: Linux
 - Crate and other dependencies: git master

**Additional**

Compile error:

```
❯ cargo build --target wasm32-unknown-unknown --example pathfinding --features algorithm
   Compiling bevy_entitiles v0.6.1 (/home/m/dev/rs/bevy_entitiles)
error[E0271]: type mismatch resolving `<Vec<(Entity, FakeTask)> as IntoIterator>::Item == (Entity, Task<Path>)`
   --> src/algorithm/pathfinding.rs:285:32
    |
285 |             queue.tasks.extend(tasks);
    |                         ------ ^^^^^ expected `(Entity, Task<Path>)`, found `(Entity, FakeTask)`
    |                         |
    |                         required by a bound introduced by this call
    |
    = note: expected tuple `(bevy::prelude::Entity, Task<pathfinding::Path>)`
               found tuple `(bevy::prelude::Entity, FakeTask)`
note: required by a bound in `extend`
   --> /home/m/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:372:31
    |
372 |     fn extend<T: IntoIterator<Item = A>>(&mut self, iter: T);
    |                               ^^^^^^^^ required by this bound in `Extend::extend`

error[E0308]: mismatched types
   --> src/algorithm/wfc.rs:654:29
    |
654 |             .insert(WfcTask(task))
    |                     ------- ^^^^ expected `Task<Option<WfcData>>`, found `FakeTask`
    |                     |
    |                     arguments to this struct are incorrect
    |
    = note: expected struct `Task<std::option::Option<WfcData>>`
               found struct `FakeTask`
note: tuple struct defined here
   --> src/algorithm/wfc.rs:636:12
    |
636 | pub struct WfcTask(Task<Option<WfcData>>);
    |            ^^^^^^^

Some errors have detailed explanations: E0271, E0308.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `bevy_entitiles` (lib) due to 2 previous errors
```

**Comment by 443eb9** [comment]
I tried to reinstall rust, remove the `.cargo/registry/src` folder, and `cargo clean`, but still cannot compile with the target `wasm32-unknown-unknown`... It threw thousands of errors saying that built in types like `Some`, `Ok` can't be found in external libraries.

I checked the source code of bevy, and found that `FakeTask` will be enabled when `any(target_arch = "wasm32", not(feature = "multi-threaded"))`. So instead of trying to targeting `wasm32`, I disabled `multi-threaded` feature, and get the same compilation error as yours.

I'm planning to reconstruct the pathfinding module, so this issue may not be solved that quickly. And as `wasm32` doesn't support stuff like `AsyncComputeTaskPool`, I'd like to do some optimization for it.

**Comment by martinlindhe** [comment]
Thanks for having a look!

That is interesting. What OS are you compiling on, maybe that's related? I'm on Linux and compiled with rust 1.76.0 (latest stable).

**Comment by 443eb9** [comment]
I'm using windows with the latest rust toolchain, and I'm planning to install arch linux & windows dual boot (on 2 separated disk) this weekend. I will try to compile with the wasm32 target again after I finished installation.

**Comment by 443eb9** [comment]
Well, I still can't compile with wasm target on Arch Linux. It shows the same error. So I will simply disable `multi-threading` to simulate your situation. Hope they are the same in this situation.

**Comment by 443eb9** [comment]
Fixed in master, feel free to reopen if the issue still exists.
