### ISSUE TITLE
Documentation on using LDTK for 2d, top-down

### ISSUE THREAD

**Issue by Ladvien** [443eb9/bevy_entitiles#18]
I greatly appreciate this plugin!  Especially the dedication to keeping it up to date.  That stated, I'm struggling with some holes in the documentation--once I've learned some more, happy to send a PR to help improve the docs. 

Here's my current problem. I'm trying to us the LDTK feature to load a map.  Everything is going well, but it seems the walls in the IntGrid are not having the component I've attached.  Ultimately, I need a `Wall` component to be attached to buildings and structure for blocking.

Problem stated, here's what I've seen.  In the `ldtk` example it seems entities have structs attached when the map is loaded, however, I can't seem the right combination to get these components attached to tiles.

```rust
App::new()
       ...
        .register_type::<Player>()
        .register_type::<Wall>() 
        .register_ldtk_entity::<Wall>("walls")
        .init_resource::<CameraControl>(
        .insert_resource(Msaa::Off)
        .insert_resource(LdtkLoadConfig {
            file_path: "assets/testy2.ldtk".to_string(),
            filter_mode: FilterMode::Nearest,
            ..Default::default()
        })
        .run();
...
#[derive(Component, LdtkEntity, Default, Reflect)]
pub struct Wall;
```

In the example I see the
```rust
        .insert_resource(LdtkAdditionalLayers {
            physics_layer: Some(LdtkPhysicsLayer {
                identifier: "PhysicsColliders".to_string(),
                air: 0,
                parent: "Collisions".to_string(),
                tiles: Some(HashMap::from([
                    (
                        1,
                        PhysicsTile {
                            rigid_body: true,
                            friction: Some(0.9),
                        },
                    ),
                    (
                        2,
                        PhysicsTile {
                            rigid_body: true,
                            friction: Some(0.1),
                        },
                    ),
                ])),
            }),
            ..Default::default()
        })
```
Is this _just_ for just adding a physics engine?  Or should it also be used for creating blocking tiles?  I saw this bit in the docs,
> ldtk Introduces the way to load/unload/switching between LDtk levels, and some **extra functionalities including automatically generate the PathTilemap and PhysicsTilemap according to the specific int grid layers**, map the tile_id to animations.

So I wouldn't think I'd need to create a hash map of the values, unless I wanted more granular controls of their physics.

Anyway, any nudges towards the correct direction would be greatly appreciated, as I'm very much enjoying the plugin!  And if I'm asking the wrong question, forgive me.  I'm moonlighting game dev.

<img width="988" alt="image" src="https://github.com/443eb9/bevy_entitiles/assets/6241517/5df3a9c0-d30e-46a8-a892-45da114910af">

<img width="398" alt="image" src="https://github.com/443eb9/bevy_entitiles/assets/6241517/3ee399a8-d1ee-47ce-8769-092f7c1ba580">

**Comment by 443eb9** [comment]
First of all, thanks a lot for supporting this crate, and I'm very glad to know that you're willing to improve the docs. I know the document part of this crate is unsatisfactory...

I'm not very sure about what do you want to achieve. Are you going to add a `Wall` component to the colliders generated according to the IntGrid? Well, that's not supported currently.

`LdtkEntity`s are **only** the entities in **LDtk** (like the green flag in the example), not the entities in bevy (like the collider tiles in your case).

Anyway, you will be able to add `Wall`s to colliders in the next commit to `master` branch.

**Comment by Ladvien** [comment]
Thank you for the quick response, 443eb9!

I'm trying to create a straightforward top-down, 2d game.  No physics, just good old paths and walls.  I'm thinking SNES Zelda.  And no worries on the lack of documentation, I get it.  You're only one person.  And your work on this create is immense!

If my use case isn't yet supported, not a problem.  I'll toggle on my patience and standby--feel free to close this out if that's the case.

Anyway, I hope my requests don't discourage you one bit.  Awesome crate! 😁

**Comment by 443eb9** [comment]
Implemented `PhysicsTileSpawn` event in `master` branch.

Closed not because this is has not supported yet, but this has already supported. :p

**Comment by 443eb9** [comment]
Btw this is not a LDtk specific feature. You can use this whenever you spawn physics tiles. Have fun coding!
