### ISSUE TITLE
Support hexagonal tilemaps?

### ISSUE THREAD

**Issue by feelingsonice** [443eb9/bevy_entitiles#2]
This repo looks extremely useful for me. Any chance you could support hexagonal tilemaps?

**Comment by 443eb9** [comment]
Yeah I will right after I finishing ldtk support. But hexagon is a special shape so I need to adapt all those logic to hexagon specifically. I think I can done hex map support in one week.

**Comment by 443eb9** [comment]
Supported in 0.2.4
