### ISSUE TITLE
Doc: 'Warning' is misspelt as Warining

### ISSUE THREAD

**Issue by Logabe** [443eb9/bevy_entitiles#23]
**Location**
`README.md`

**Actual Behavior**
The header '`warining`' seems to be a spelling mistake. The correct word would be `warning`. If this is intentional, please feel free to dismiss this issue. If it isn't, I'll happily create a pull request to fix this.

(I know how silly it is to file an issue over so minor a mistake, I hope I'm not wasting your time)

**Comment by 443eb9** [comment]
Well, that's kinda embarrassing especially when it's a title which is bold and larger 😂

Thanks for reminding me, I can fix that by myself. By the way any issues are welcomed, as they all show your concern to this project. :heart:
