### ISSUE TITLE
Migrate to Avian for physics

### ISSUE THREAD

**Issue by musjj** [443eb9/bevy_entitiles#35]
Bevy XPBD has been [deprecated](https://docs.rs/bevy_xpbd_2d):

> Bevy XPBD (deprecated in favor of [Avian](https://github.com/Jondolf/avian))
> 
> ⚠️ Bevy XPBD has been deprecated in favor of its successor [Avian](https://github.com/Jondolf/avian). No further development or maintenance will be done for Bevy XPBD. See [#346](https://github.com/Jondolf/avian/issues/346) for background.

The API is mostly (if not completely) backwards-compatible AFAIK, so migration shouldn't be too hard.

**Comment by 443eb9** [comment]
I have already done this, but forgot to merge `dev` branch. Now you can use `avian2d` for physics backend with `entitiles` in `master` branch.
