### ISSUE TITLE
Bug: Y Sort not implement

### ISSUE THREAD

**Issue by darkautism** [443eb9/bevy_entitiles#37]
**Description**
Y Sort not implement

**Reproduction**
Create a map with a tile which with large than grid size will very easy reproduce.

**Screenshots**
![image](https://github.com/user-attachments/assets/ecd5f722-ad06-48b2-acec-1597cb7d2edd)
![image](https://github.com/user-attachments/assets/ccfb56f2-14c7-4fe3-8230-158abfe4917d)

**Versions**
 - OS: Windows10
 - Crate and other dependencies: master

**Additional**
After apply ysort, it is useful to export y-sort component as public when user add player or enemy object.

**Comment by 443eb9** [comment]
Provided a solution in `master` branch.

You can now use `TilemapStorage::rearrange(1)` to reset the chunk size of tilemaps, and don't forget to insert `RenderChunkSort::XReverseThenYReverse` resource. For more information, please check `isometric_cube` example.

In the future, there might be better solutions, like using depth texture? I'm not very sure about this. But currently, rendering sorted tilemaps is not efficient...

I'm going to close this issue. Feel free to reopen it if you have any other questions.

Edit:

Pretty sure this would get improved using depth texture in bevy 0.15. Just found that bevy split transparent and opaque mesh2ds in 0.15, and added depth texture in pass.
