### ISSUE TITLE
Consider a prelude?

### ISSUE THREAD

**Issue by piedoom** [443eb9/bevy_entitiles#5]
This is a great project - I apologize if this is not a wanted issue type, please delete if so. I noticed that many of the examples use a lot of imports to the point of being >10 lines. Would you consider creating a prelude such as bevy's prelude to export all useful types?

**Comment by 443eb9** [comment]
> I apologize if this is not a wanted issue type, please delete if so.

No no no, this is a good idea. I will add that in the next version.

Your ideas (issues/prs/or even just messages you send on discord) to improve the project, no matter whose, will always be appreciated. So please feel free to make suggestions! There doesn't exist any reason for you to apologize.

**Comment by 443eb9** [comment]
Added in 0.2.5
