### ISSUE TITLE
Relax dependencies

### ISSUE THREAD

**Issue by myOmikron** [443eb9/bevy_entitiles#6]
Hi there,

I think it would be nice, if you could relax the versions of the dependencies of your crate. 
Most of rusts ecosystem is using [semver](https://semver.org/) and follow its versioning quite strictly.

I'd exclude bevy related crates as some of them follow bevys schema to make it easier selecting the correct version.

**Comment by 443eb9** [comment]
Thanks for reminding me that. I'm just to dedicated to latest versions. I will change them in the next version.

Also the `semver` versioning is quite good but I didn't know that before. I think I'd better follow that when versioning `entitiles`.

**Comment by 443eb9** [comment]
Changed in 0.3.0
